spring.application.name=demo

#=============================
# Fonte de dados
#=============================
# Informações para a conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_controle_epis
spring.datasource.username=postgres
#Credencial de banco local de desenvolvimento, mantida proprositalmente para fins de portifólio no GitHub.
spring.datasource.password=gus56a
#A baixo dizemos pro java usar tradutor oficial do banco para conseguir conversar com o banco
spring.datasource.driver-class-name=org.postgresql.Driver


#=============================
# JPA / Hibernação
#=============================
# Sempre que um comando SQL for executado sera monstraddo na tela da IDE para poder ser virificado
spring.jpa.show-sql=true
#
# Quando for necessario criar uma nova coluna essa função fica responsavel e garante que os dados não serão apagados
spring.jpa.hibernate.ddl-auto=update
#Essa linha garante que os comandos sql usados serão exclusivamnte do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
