spring.application.name=demo

#=============================
# Fonte de dados
#=============================
# Informações para a conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_controle_epis
spring.datasource.username=postgres
# Credencial de banco local de desenvolvimento, mantida propositalmente para fins de portfólio no GitHub.
spring.datasource.password=gus56a
# Define o driver JDBC oficial usado para a conexão com o banco de dados PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver


#=============================
# JPA / Hiberna��o
#=============================
# Exibe no console da IDE cada comando SQL executado, útil para depuração
spring.jpa.show-sql=true
#
# Quando for necessário criar uma nova coluna, essa função fica responsável e garante que os dados não serão apagados
spring.jpa.hibernate.ddl-auto=update
# Essa linha garante que os comandos SQL usados serão exclusivamente do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
